# Generated by Django 5.2.7 on 2025-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(default='1999-01-01')),
            ],
            options={
                'verbose_name': 'Disciplina',
            },
        ),
    ]
